### ISSUE TITLE
Creating RestAPI to delete files or file folder by applying Transaction mechanism

### ISSUE THREAD

**Issue by jeanniewang** [fiosman/meFilez#13]
When deleting a nested file folder, all its child files, and file folder needs to be deleted at one time. If this deletion task is broken in the middle, there will be orphaned files or file folders. Therefore, the transaction mechanism needs to be implemented to make this process atomic: if any step fails, the whole process will rollback, any deleted files will be recovered.
 
The primary goal of a transaction is to let you update multiple documents in MongoDB in isolation, and potentially undo all the updates if some error occurs by aborting the transaction.

https://mongoosejs.com/docs/transactions.html
https://thecodebarbarian.com/whats-new-in-mongoose-5-10-improved-transactions.html

**Comment by jeanniewang** [comment]
One challenge posing to this task is to efficiently find all the child files and file folders within a nested root folder. 

The fileSchema needs to be revised first to achieve this purpose. Currently, fileSchema only has A reference to its parent id. Then the time complexity is O(2^n) for either wide search or deep search if the depth of the nested folder is n. Plus constantly making find by parentID query to the database would make it the least desirable approach.

An efficient approach is to add an ancestor array in the fileSchema to trace all its ancestors. parentsIds[0] refers to its oldest  parent, parents[1] refers to its second oldest parent, parentsId[n - 1] refers to its parent. To delete a folder, the filter is to append this folder's file object id to the ancestor array of itself, then using this filter to find and delete all subfolders or files whose ancestor array matches; then delete this target folder in the end.

Note, the ancestor needs to be indexed. 

This approach achieves a good balance between time and space complexity.  The Space complexity is O(n * (n ^2)), while time complexity O(n).   n is the depth of the nested folder from the highest user level. If there are 1000 files belonging to one user, then the n = 10.

**Comment by jeanniewang** [comment]
Suggest using Model.deleteMany({ancestor filter}) if transaction session works with this query method; if not, using Model.find({acesotr filter}) to retrieve all subfolders and files, then delete them one by one using Model.deleteOne.

**Comment by fiosman** [comment]
delete-files merged into main
