### ISSUE TITLE
Git-Feature-Branch-Workflow-Training

### ISSUE THREAD

**Issue by jeanniewang** [fiosman/meFilez#3]
Description: This ticket is to go through each step of the Git Feature Branch Workflow.  Atlassian offered an excellent explanation:
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow 

The core idea behind Git Feature Branch Workflow is that all feature development should take place in a dedicated branch instead of the master branch.

Task one: Example with creating any conflict:
- Work on your new branch
   Create a branch from the master branch
   Create a new-branch 
   Update, add, commit, and push changes
   Push feature branch to remote
- Create a pull request for your feature branch
- Merge the pull request

Task two: Example with creating some conflict and need to resolve:
This is just to repeat the previous steps, however,  the task performer should intentionally skip updating the origin/main branch.

More reference:
https://guides.github.com/introduction/flow/ (Nice diagram)
https://gist.github.com/blackfalcon/8428401 (Solutions to resolve conflict: Merge vs Rebase)

**Comment by fiosman** [comment]
I don't understand rebasing. Why can't we just pull? We should go into this in more detail. 

I've completed all assigned training, and I have already created several pull requests for features I have worked on.
